version: "3.8"

services:
  db:
    image: orientdb:latest
    container_name: orient_db_container
    ports:
      - "2424:2424"
      - "2480:2480"
    environment:
      ORIENTDB_ROOT_USERNAME: admin
      ORIENTDB_ROOT_PASSWORD: admin
      ORIENTDB_ROOT_EMAIL: root@example.com
    volumes:
      - orientdb_data:/orientdb/databases
    networks:
      - orient
    restart: always

  postgres:
    image: postgres:12-alpine
    container_name: my_postgres_db
    ports:
      - "5555:5432"
    environment:
      POSTGRES_DB: session
      POSTGRES_PASSWORD: "123456"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - orient
    restart: always

  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark
    ports:
      - "4040:4040" # Spark UI
      - "6066:6066" # Spark Master
      - "7077:7077" # Spark Master Web UI
      - "8080:8080" # Spark Worker Web UI
      - "8081:8081" # Spark Application UI
    networks:
      - orient
    volumes:
      - ./apps:/opt/spark-apps
      - ./data:/opt/spark-data

  spark-worker:
    container_name: spark-worker
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - HIVE_CORE_CONF_javax_jdo_option_ConnectionURL=jdbc:orient:remote:localhost
    depends_on:
      - spark-master
    networks:
      - orient
    volumes:
        - ./apps:/opt/spark-apps
        - ./data:/opt/spark-data

  namenode:
    image: sequenceiq/hadoop-docker:2.7.1
    container_name: namenode
    command: /etc/bootstrap.sh -d
    ports:
      - "50070:50070"
    volumes:
      - ./data/hdfs/namenode:/opt/hadoop-2.7.1/data/hdfs/namenode
    environment:
      - CLUSTER_NAME=hadoop-cluster
      - HADOOP_HOME="/usr/local/hadoop"
      - HADOOP_MAPRED_HOME=$HADOOP_HOME
      - HADOOP_COMMON_HOME=$HADOOP_HOME
      - HADOOP_HDFS_HOME=$HADOOP_HOME
      - YARN_HOME=$HADOOP_HOME
      - HADOOP_COMMON_LIB_NATIVE_DIR=$HADOOP_HOME/lib/native
      - PATH=$PATH:$HADOOP_HOME/sbin:$HADOOP_HOME/bin
    networks:
      - orient

  datanode1:
    container_name: datanode1
    image: sequenceiq/hadoop-docker:2.7.1
    command: /etc/bootstrap.sh -d
    volumes:
      - ./data/hdfs/datanode1:/opt/hadoop-2.7.1/data/hdfs/datanode
    environment:
      - CLUSTER_NAME=hadoop-cluster
      - SERVICE_PRECONDITION=startup_datanode1:namenode:50070
      - HADOOP_HOME="/usr/local/hadoop"
      - HADOOP_MAPRED_HOME=$HADOOP_HOME
      - HADOOP_COMMON_HOME=$HADOOP_HOME
      - HADOOP_HDFS_HOME=$HADOOP_HOME
      - YARN_HOME=$HADOOP_HOME
      - HADOOP_COMMON_LIB_NATIVE_DIR=$HADOOP_HOME/lib/native
      - PATH=$PATH:$HADOOP_HOME/sbin:$HADOOP_HOME/bin
    depends_on:
      - namenode
    networks:
      - orient
volumes:
  postgres:
  orientdb_data:
  apps:
  data:

networks:
  orient:
    name: orient
    driver: bridge
