version: "3.8"

services:
  db:
    image: orientdb:2.2.5
    container_name: orient_container
    ports:
      - "2424:2424"
      - "2480:2480"
    environment:
      ORIENTDB_ROOT_USERNAME: admin
      ORIENTDB_ROOT_PASSWORD: admin
      ORIENTDB_ROOT_EMAIL: root@example.com
    volumes:
      - orientdb_data:/orientdb/databases
    networks:
      - orient
    restart: always


  hadoop:
    image: harisekhon/hadoop:latest
    container_name: hadoop-container
    ports:
      - "50070:50070"  # Hadoop Namenode Web UI
      - "8088:8088"    # Hadoop ResourceManager Web UI
    networks:
      - orient

  spark:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark
    ports:
      - "4040:4040" # Spark UI
      - "6066:6066" # Spark Master
      - "7077:7077" # Spark Master Web UI
      - "8083:8080" # Spark Worker Web UI
      - "8081:8081" # Spark Application UI
    networks:
      - orient

  spark-worker:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
    networks:
      - orient

volumes:
  postgres:
  orientdb_data:

networks:
  orient:
    name: orient
    driver: bridge
